### ISSUE TITLE
Make subject link target customisable

### ISSUE THREAD

**Issue by Mar-tin-G** [Mar-tin-G/EmptyPostSubjects#4]
see https://www.phpbb.com/community/viewtopic.php?p=14400451#p14400451

> A suggestion, for future updates : in the extension control panel, coold we have the choice, if the subject title is displayed in the board index (instead of the last message title), to make it link to the subject itself, and not to the last message ?
> 
> Because we can already link to the last message with the little icon (the square with an arrow) next to the author name.

**Comment by Mar-tin-G** [comment]
This is currently not possible unfortunately. 

The phpBB 3.2 template `forumlist_body.html` defines (see [source](https://github.com/phpbb/phpbb/blob/7be590d3254a9b9252d9221a1e45b97048585a1c/phpBB/styles/prosilver/template/forumlist_body.html#L96)):

```html
<a href="{forumrow.U_LAST_POST}" title="{forumrow.LAST_POST_SUBJECT}" class="lastsubject">{forumrow.LAST_POST_SUBJECT_TRUNCATED}</a> <br />
{L_POST_BY_AUTHOR} {forumrow.LAST_POSTER_FULL}
<a href="{forumrow.U_LAST_POST}" title="{L_VIEW_LATEST_POST}">
	<i class="icon fa-external-link-square fa-fw icon-lightgray icon-md" aria-hidden="true"></i><span class="sr-only">{L_VIEW_LATEST_POST}</span>
</a>
```
The first link is the "last post subject", the second link is the small icon near the author's name. Both links use the **same** URL `U_LAST_POST`.

I created an issue at phpBB for extending this template, which would allow to implement the requested feature.

https://tracker.phpbb.com/browse/PHPBB3-15571

**Comment by Mar-tin-G** [comment]
The phpBB issue was closed, so I don't think they will change the template to make the suggestion possible.

**Comment by TB54** [comment]
Hello ! Being still interested in this feature, I was wondering if the last phpBB updates has changed something to it?

I realized it was enable (titre link to the subject, the arrow to the last mesasge) in some phpBB forums, like this one, but don't know why/how : http://forum.plan-sequence.com/
